services:
  user_service:
    image: nthuanreal/user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "5000:5000"
    volumes:
      - ./user-service:/app
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: user_service

  promotion_service:
    build:
      context: ./promotion_service
      dockerfile: Dockerfile
    container_name: promotion-service
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/promotion_service

  postgres:
    image: postgres:15
    container_name: user-service-postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: promotion_service
    volumes:
      - mysql_data:/var/lib/mysql

  game_service:
    build:
      context: ./game_service
      dockerfile: Dockerfile
    container_name: game-service
    ports:
      - "8000:8000"
    env_file:
      - ./game_service/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  postgres_data:
  mysql_data:
  mongo-data:
