# Sử dụng Node.js làm base image
FROM node:20

# Thiết lập thư mục làm việc trong container
WORKDIR /user-service

# Sao chép package.json và package-lock.json vào container
COPY package*.json ./
RUN ls -al /user-service 

# Cài đặt các dependencies
RUN npm install
RUN ls -al /user-service  

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Biên dịch dự án NestJS (nếu đang sử dụng TypeScript)
RUN npm run build

# Cấp quyền truy cập cổng cho ứng dụng (theo cổng bạn đã cấu hình trong app)
EXPOSE  ${PORT}

# Lệnh khởi chạy ứng dụng
CMD ["npm", "start"]
