version: '3.8'

services:
  promotion_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/promotion_service

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: promotion_service
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: